# Generated by Django 3.1.5 on 2021-01-19 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210119_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchedusers',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='matchedusers',
            name='user2',
        ),
        migrations.AddField(
            model_name='matchedusers',
            name='matches',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchedusers',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
