# Generated by Django 3.1.5 on 2021-01-19 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210119_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_asker', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_reveiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
